version: "3.8"

services:

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports: 
      - '${MONGO_PORT}:27017'

    volumes: 
      - "./db:/data/db"
      - ./script/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    env_file:
      - .env
      
  
