version: "3.8"

services:

  mongo:
    image: mongo
    build:
      context: ./docker
      dockerfile: DockerFile

    # restart: always
    restart: unless-stopped

    container_name: mongo-db
    ports: 
      - '${MONGO_PORT}:27017'

    volumes:
      - type: "bind"
        source: "./db"
        target: "/data/db/joLife"
      
    volumes:
      # - type: "bind"
      #   source: "./script/init.js"
      #   target: "/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - ./script/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    env_file:
      - .env
      
  
